# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc05546c2650c0583dc3e8ccda654e9083f6de089744a69969967d2c08316becd5473e2b25234f9efeb1b6289c6bfb206176c578a962303576f13a2b85c9cba8

test:
  secret_key_base: 67968f8950799a526e0137918d8861135abae7436491ffa8ba8a5a62365f21fda805cefef0959ebcb837adc7018dd2fa37c541f5deb164419fd4a5799c6353f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
